os: osx
osx_image: xcode11.2
language: node_js
node_js: '12'
script:
  - npm run travis-dist-win

git:
  submodules: false

before_install:
  - echo -e "machine github.com\n login $CI_USER_TOKEN" > ~/.netrc
  - git submodule update --init --recursive

deploy:
    provider: releases
    skip_cleanup: false
    api_key: $GH_TOKEN
    file_glob: true
    file:
      - "dist/mamd-analytical-*-mac.zip"
      - "dist/mamd-analytical-setup-*.exe"
    on:
      tags: true